go[tests]: Update all e2e tests to use the new `goeval` generator
The tests themselves were changed to compare against the pretty
printed value tree instead of the old impl of the `Value.String()`.
This was done **before** the generator was changed to ensure there
would be minimal difference.

Then, after changing the generator from `go` to `goeval`, the
following differences were reflected on the tests:

1. Purely syntactic rules are wrapped in a single Capture.  Consider
   the standard definition of the `Identifier` rule:

      Identifier <- [a-zA-Z_][a-zA-Z0-9_]*

   When matching with the word `blah` for example, the `go` generator
   would spit out a nested sequence like this one:

      Node("Identifier", ["b", ["l", "a", "h"]])

   Whereas the `goeval` generator will return something along these
   lines:

      Node("Identifier", "blah")

2. Automatic error reporting got a bit more detailed, which breaks
   tests because error messages changed (for better!). e.g.:

      Exp <- Num '+' Num
      Num <- Dec / Hex
      Dec <- [1-9][0-9]* / '0'
      Hex <- '0x' [a-fA-F0-9]+^LabelHex

   When matched against the input `3+#xC0FFEE` will produce a more
   detailed error containing what characters were expected. e.g.:

      ERROR: Expected '1-9', '0' but got '#' @ 3

NOTICE: Those two differenences do make these two generators generate
parsers that do return different output trees and error messages.
This implies that switching from `go` to `goeval` isn't a backward
compatible change and will likely entail breaking application tests.